/**:
  ros__parameters:
    depth:
      frame_id: "iphone_depth"
    color:
      frame_id: "iphone_color"
    confidence:
      pub_flag: True
      frame_id: "camera"
    pose:
      pub_flag: True
      frame_id: "camera"
    cloud:
      pub_flag: True
      frame_id: "camera"