/**:
  ros__parameters:
    depth:
      pub_flag: True
      frame_id: "camera"
    color:
      pub_flag: True
      frame_id: "camera"
    confidence:
      pub_flag: True
      frame_id: "camera"
    pose:
      pub_flag: True
      frame_id: "camera"
    cloud:
      pub_flag: True
      frame_id: "camera"